services:
  next-app:
    container_name: juanisadev
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - ASSISTANT_ID=${ASSISTANT_ID}
    env_file:
      - .env
    restart: always
    ports:
      - "3001:3001"
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    driver: bridge