import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/index.scss";
import Navbar from "@components/navigation/navbar";
import { Providers } from "@app/providers";
import { Skeletons } from "@components/skeletonTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className={"app"}>

					<Providers><Skeletons><Navbar />{children}</Skeletons></Providers>
				</div>
			</body>
		</html >
	);
}
